export const tags = [
  "media",
  "video tools",
  "utility",
  "photo tools",
  "customization",
  "advanced",
  "streaming",
  "social",
  "widgets and shortcuts",
  "audio tools",
  "automation",
  "productivity",
  "icon packs",
  "system tools",
  "file management",
  "ringtones",
  "wallpapers",
  "launcher",
  "shizuku",
] as const;

export type TagList = (typeof tags)[number][];

type ArrayToStringUnion<T extends readonly string[]> = T[number];

export const apps: {
  name: string;
  description: string;
  icon: string;
  tags: ArrayToStringUnion<typeof tags>[];
  link: string;
  hex: string;
}[] = [
  {
    name: "DarQ",
    description: "Advanced 'force dark' mode customization.",
    icon: "darq",
    tags: ["customization", "advanced", "shizuku"],
    link: "https://github.com/KieronQuinn/DarQ/releases/latest",
    hex: "212325",
  },
  {
    name: "CloudStream",
    description: "Media streaming app for shows and movies.",
    icon: "cloudstream",
    tags: ["media", "streaming", "video tools"],
    link: "https://github.com/recloudstream/cloudstream",
    hex: "000004",
  },
  {
    name: "Instander",
    description: "Modified Instagram app with additional features.",
    icon: "instander",
    tags: ["social", "advanced", "media"],
    link: "https://t.me/thedise/1967",
    hex: "ffffff",
  },
  {
    name: "KLWP",
    description: "Tool for creating custom live wallpapers.",
    icon: "klwp",
    tags: ["customization", "widgets and shortcuts"],
    link: "https://play.google.com/store/apps/details?id=org.kustom.wallpaper",
    hex: "b22a52",
  },
  {
    name: "KWGT",
    description: "Tool for creating custom widgets.",
    icon: "kwgt",
    tags: ["customization", "widgets and shortcuts"],
    link: "https://play.google.com/store/apps/details?id=org.kustom.widget",
    hex: "2b73af",
  },
  {
    name: "Musicolet",
    description: "Offline music player with advanced features.",
    icon: "musicolet",
    tags: ["media", "audio tools"],
    link: "https://play.google.com/store/apps/details?id=in.krosbits.musicolet",
    hex: "65ffa0",
  },
  {
    name: "NFC Tools",
    description: "App for creating and managing NFC tasks.",
    icon: "nfc_tools",
    tags: ["utility", "automation", "advanced"],
    link: "https://play.google.com/store/apps/details?id=com.wakdev.wdnfc",
    hex: "36445c",
  },
  {
    name: "Niagara Launcher",
    description: "Minimalist and efficient Android launcher.",
    icon: "niagara_launcher",
    tags: [
      "customization",
      "productivity",
      "widgets and shortcuts",
      "utility",
      "launcher",
    ],
    link: "https://play.google.com/store/apps/details?id=bitpit.launcher",
    hex: "01001e",
  },
  {
    name: "Panda Video Compressor",
    description: "Tool to compress videos on-device.",
    icon: "panda_video_compressor",
    tags: ["media", "video tools", "utility"],
    link: "https://play.google.com/store/apps/details?id=com.pandavideocompressor",
    hex: "8955c4",
  },
  {
    name: "Pixel Search",
    description: "Powerful all-in-one search.",
    icon: "pixel_search",
    tags: ["utility", "productivity"],
    link: "https://play.google.com/store/apps/details?id=rk.android.app.pixelsearch",
    hex: "fff2f0",
  },
  {
    name: "Pix Material You (Dark/Light)",
    description: "Icon pack inspired by Material You design.",
    icon: "pix_material_you",
    tags: ["customization", "widgets and shortcuts", "icon packs"],
    link: "https://play.google.com/store/apps/details?id=com.pashapuma.pix.material.you.dark",
    hex: "2f3d54",
  },
  {
    name: "Polycam",
    description: "3D scanning app for capturing objects and environments.",
    icon: "polycam",
    tags: ["media", "photo tools"],
    link: "https://play.google.com/store/apps/details?id=ai.polycam",
    hex: "fffff7",
  },
  {
    name: "Quick Settings",
    description: "Tool to customize and manage quick settings toggles.",
    icon: "quick_settings",
    tags: ["customization", "widgets and shortcuts", "utility"],
    link: "https://play.google.com/store/apps/details?id=it.simonesestito.ntiles",
    hex: "354042",
  },
  {
    name: "ReVanced Manager",
    description: "App for modding YouTube and other media platforms.",
    icon: "revanced_manager",
    tags: ["social", "advanced", "streaming", "media"],
    link: "https://revanced.app/",
    hex: "1b1d1c",
  },
  {
    name: "Seal",
    description: "Versatile app for video downloading.",
    icon: "seal",
    tags: ["media", "video tools", "utility"],
    link: "https://github.com/JunkFood02/Seal/releases/latest",
    hex: "fefefe",
  },
  {
    name: "Shortcut Maker",
    description: "App for creating custom shortcuts.",
    icon: "shortcut_maker",
    tags: ["customization", "widgets and shortcuts", "automation"],
    link: "https://play.google.com/store/apps/details?id=rk.android.app.shortcutmaker",
    hex: "ffffff",
  },
  {
    name: "Shizuku",
    description: "System tool for advanced Android modifications.",
    icon: "shizuku",
    tags: ["advanced", "system tools", "shizuku"],
    link: "https://play.google.com/store/apps/details?id=moe.shizuku.privileged.api",
    hex: "4053b5",
  },
  {
    name: "Smartspacer",
    description: "Customization tool for extending Pixel's At a Glance.",
    icon: "smartspacer",
    tags: [
      "customization",
      "widgets and shortcuts",
      "utility",
      "advanced",
      "shizuku",
    ],
    link: "https://github.com/KieronQuinn/Smartspacer",
    hex: "ffffff",
  },
  {
    name: "Stats.fm",
    description: "Analytics tool for tracking your music listening habits.",
    icon: "stats_fm",
    tags: ["media", "audio tools", "productivity"],
    link: "https://play.google.com/store/apps/details?id=dev.netlob.spotistats",
    hex: "181413",
  },
  {
    name: "SuperImage",
    description: "Image enhancement tool.",
    icon: "superimage",
    tags: ["media", "photo tools", "utility"],
    link: "https://play.google.com/store/apps/details?id=com.zhenxiang.superimage",
    hex: "ffffff",
  },
  {
    name: "System UI Tuner",
    description: "Tool for editing the hidden SystemUI settings.",
    icon: "system_ui_tuner",
    tags: ["customization", "advanced", "shizuku"],
    link: "https://play.google.com/store/apps/details?id=com.bryancandi.android.uituner",
    hex: "ffffff",
  },
  {
    name: "Tasker",
    description:
      "Powerful automation app for creating and managing advanced tasks.",
    icon: "tasker",
    tags: ["automation", "utility", "advanced", "productivity", "shizuku"],
    link: "https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm",
    hex: "371a4d",
  },
  {
    name: "Termux",
    description: "Linux terminal emulator.",
    icon: "termux",
    tags: ["utility", "advanced", "productivity"],
    link: "https://github.com/termux/termux-app?tab=readme-ov-file#installation",
    hex: "000000",
  },
  {
    name: "Total Commander",
    description: "Powerful old-school file manager.",
    icon: "total_commander",
    tags: ["file management", "utility"],
    link: "https://play.google.com/store/apps/details?id=com.ghisler.android.TotalCommander",
    hex: "fdffff",
  },
  {
    name: "Unified Remote",
    description: "Remote control app for managing your PC from your phone.",
    icon: "unified_remote",
    tags: ["utility", "productivity"],
    link: "https://www.unifiedremote.com/download",
    hex: "419b23",
  },
  {
    name: "Wavelet",
    description: "Sound equalizer for fine-tuning audio playback.",
    icon: "wavelet",
    tags: ["media", "audio tools", "customization"],
    link: "https://play.google.com/store/apps/details?id=com.pittvandewitt.wavelet",
    hex: "10130f",
  },
  {
    name: "Zedge",
    description: "App for ringtones, wallpapers, and other customizations.",
    icon: "zedge",
    tags: ["media", "customization", "ringtones", "wallpapers"],
    link: "https://play.google.com/store/apps/details?id=net.zedge.android",
    hex: "6837dd",
  },
];
